CREATE DATABASE JSON_AND_FETCH;
USE jSON_AND_FETCH;

CREATE TABLE CLIENTES(
CLI_ID INT AUTO_INCREMENT,
CLI_NOMBRE VARCHAR(25),
CLI_APELLIDO VARCHAR(25),
CLI_EDAD INTEGER(3),
PRIMARY KEY(CLI_ID));

INSERT INTO CLIENTES (CLI_NOMBRE, CLI_APELLIDO, CLI_EDAD) VALUES ("Alejandra", "Herman", 46);

SELECT CLI_ID FROM CLIENTES WHERE CLI_NOMBRE = "German" AND CLI_APELLIDO = "Canteros";